### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by lynxul25** [BigFoot2020/daikin_residential_brp069a62#11]
Hi,

It would be absolutely awesome if you could pull the error status (as published to the cloud and reported by the onecta official app)

**Comment by lynxul25** [comment]
![Screenshot_20230203-185246](https://user-images.githubusercontent.com/96091349/216661118-2d6eef61-94f9-4ea5-9fb6-cf5f27e3d9c3.png)

**Comment by BigFoot2020** [comment]
Would you be able to check if this error status/code exists in daikin_puredata.json file (in HA config folder)?
Error condition should be active, if it is fixed it would not be there anymore.
If it is there, then extract from section with error, would help.

**Comment by BigFoot2020** [comment]
Please try "Daikin Residential for Altherma 3" integration (see main readme) as this already has Error Code sensor implemented and should now support.
