### ISSUE TITLE
Water pressure

### ISSUE THREAD

**Issue by nval34** [BigFoot2020/daikin_residential_brp069a62#12]
Thanks for you integration that seems to work well (installed less than 1 day !!!)

Could you provide HA integration the water pressure ?

Thanks

**Comment by BigFoot2020** [comment]
Not likely. My own device does not have water pressure sensor at all, so I don't see it anywhere. 
What you cold check: Do you see water pressure anywhere in ONECTA (Daikin) app?
If so, then is the pressure also present in daikin_puredata.json file (in HA config folder)?
If water pressure is not there, then it cannot be added.

**Comment by nval34** [comment]
I do not have access to this data in ONECTA :(
Thank you
