### ISSUE TITLE
Daikin intergratie not connecten with beta 2

### ISSUE THREAD

**Issue by Homeassistjoenka** [BigFoot2020/daikin_residential_brp069a62#14]
We have Install the beta 2 and now its the daikin cloud not connected how can this? Can you this fix it?

**Comment by BigFoot2020** [comment]
This repository is not developed anymore and will be archived soon as noted in ReadMe. You should use "Daikin Residential for Altherma" integration (https://github.com/speleolontra/daikin_residential_altherma) and if it still does not work correctly, create issue on that repository.
