### ISSUE TITLE
Works on BRP069A61

### ISSUE THREAD

**Issue by qazqazie** [BigFoot2020/daikin_residential_brp069a62#2]
Hello, 

I got this working on BRP069A61, I have 10 entities as shown in the screenshot. Many thanks to all involved in getting this working.

I have not tried any automation yet so only suggestion is maybe add a button to enable the holiday schedule.

Thanks again
Brian

**Comment by qazqazie** [comment]
Forgot the screenshot
![Screenshot_2021-12-31-16-52-46-451_io homeassistant companion android](https://user-images.githubusercontent.com/76488780/147831584-00ef1a3d-a9a5-43b0-9279-9187872f6c8f.jpg)

**Comment by BigFoot2020** [comment]
Hello!

As I have never used holiday mode and it is not shown in my heatpump menu, would you be willing to share your JSON data (daikin_puredata.json in HA /config folder) with holiday mode enabled and then disabled? Either here, with PII (IDs, serial, MAC, IP) removed, or via some other method (pivate repo maybe)?

Also description how you enable it would help?

**Comment by homeyjoenka** [comment]
> Hallo,
> 
> Ik heb dit werkend gekregen op BRP069A61, ik heb 10 entiteiten zoals weergegeven in de schermafbeelding. Veel dank aan alle betrokkenen om dit werkend te krijgen.
> 
> Ik heb nog geen automatisering geprobeerd, dus de enige suggestie is om misschien een knop toe te voegen om het vakantieschema in te schakelen.
> 
> Nogmaals bedankt Brian

**Comment by homeyjoenka** [comment]
Hi 
How can you see the program?

- [ ] ![0ECB4CFF-BE6D-4369-858D-660D99C0BAAF](https://user-images.githubusercontent.com/61145850/163362487-85926a44-4c8c-4ab2-858a-ca167784634f.png)

**Comment by homeyjoenka** [comment]
We have only this 
![8D0C7F2C-CA29-40B8-9F8B-BF931DBEC5A1](https://user-images.githubusercontent.com/61145850/163363082-3a682903-db72-48cf-9559-4385a18de014.jpeg)
![CC92CA72-DE27-474D-A6F7-A78697AD0312](https://user-images.githubusercontent.com/61145850/163363100-c982f1ac-c40e-405c-afe1-4e200959725c.jpeg)
En you have the program icon

**Comment by BigFoot2020** [comment]
Hello!

Marked button chooses operation mode "Auto" (others are Heating, Cooling and Off). It has nothing to do with program/schedule.

I did look if it would be possible to support holiday mode and/or schedules, but it was too complicated for me at that point. Since I don't use these myself, I have no plan to implement it. You are welcome to try to add it yourself, if you can figure out a solution.

**Comment by homeyjoenka** [comment]
Oké thank you 
I have two different models of wifi modules do you have that too?
![5C56B119-4F49-4D9E-91F5-E9945DECC239](https://user-images.githubusercontent.com/61145850/163454801-eda550ba-4b7b-47cb-a566-28dd9142ccd2.jpeg)
![441F2166-BA70-4EEC-9001-3367B6C862B0](https://user-images.githubusercontent.com/61145850/163454804-56400bcf-dd05-428b-9fea-1ea600d23957.jpeg)

**Comment by BigFoot2020** [comment]
No, I only have one Daikin device with LAN Adapter, no Wifi.

You may want to look at other integrations:
Daikin ACs via Daikin Residential Cloud:https://github.com/rospogrigio/daikin_residential
Daikin heatpumps with wifi adapters via cloud: https://github.com/speleolontra/daikin_residential_altherma
Daikin BRP069A61/2 locally via WebSocets: https://github.com/tadasdanielius/daikin_altherma
