### ISSUE TITLE
Support for gas condensing boiler D2CND with gateway DRGATEWAYAA and room thermostat DOTROOMTHEAA

### ISSUE THREAD

**Issue by mihsu81** [BigFoot2020/daikin_residential_brp069a62#4]
Hi @BigFoot2020,

Would you be able to add support for a gas condensing boiler D2CND with gateway DRGATEWAYAA and room thermostat DOTROOMTHEAA? Or at least give me some hints on how i could integrate it? 🙂
At the moment the hot water setpoint and inside temperature are detected, as well as the on/off controls of room and water heating.
![image](https://user-images.githubusercontent.com/40715497/155106272-64abe8cf-8e0b-48c2-ab1a-41688be2f62d.png)

The climate and water_heater entities don't get created because of 2 errors.
```
Log Details (ERROR)
Logger: homeassistant.components.climate
Source: custom_components/daikin_residential_brp069a62/daikin_base.py:259
Integration: Climate (documentation, issues)
First occurred: 11:14:38 AM (2 occurrences)
Last logged: 11:14:38 AM

Error adding entities for domain climate with platform daikin_residential_brp069a62
Error while setting up daikin_residential_brp069a62 platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 514, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 226, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/daikin_residential_brp069a62/climate.py", line 173, in hvac_modes
    return self._device.hvac_modes
  File "/config/custom_components/daikin_residential_brp069a62/daikin_base.py", line 259, in hvac_modes
    modes.append(DAIKIN_HVAC_TO_HA[mode])
KeyError: 'heatingDay'
```
```
Logger: homeassistant.components.water_heater
Source: custom_components/daikin_residential_brp069a62/daikin_base.py:141
Integration: Water Heater (documentation, issues)
First occurred: 11:14:38 AM (2 occurrences)
Last logged: 11:14:38 AM

Error adding entities for domain water_heater with platform daikin_residential_brp069a62
Error while setting up daikin_residential_brp069a62 platform for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 782, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 204, in state_attributes
    self.current_temperature,
  File "/config/custom_components/daikin_residential_brp069a62/water_heater.py", line 118, in current_temperature
    return self._device.dhw_temperature
  File "/config/custom_components/daikin_residential_brp069a62/daikin_base.py", line 141, in dhw_temperature
    return float(self.getValue(ATTR_DHW_TEMPERATURE))
TypeError: float() argument must be a string or a number, not 'NoneType'
```
For the climate entity, _operationMode_ would have to be sent as _heating_ instead of _heatingDay_ and _heatingNight_.

```
                "operationMode": {
                    "settable": true,
                    "value": "heatingNight",
                    "values": [
                        "heatingDay",
                        "heatingNight"
                    ]
```

Here's the json file.
[daikin_puredata.zip](https://github.com/BigFoot2020/daikin_residential_brp069a62/files/8115882/daikin_puredata.zip)

Thanks in advance.

**Comment by BigFoot2020** [comment]
Hello!

I have not been able to figure out how to make this component work for other setups, not enough time or motivation (as I'm currnetly using another component with local control). I can give you hints how to get climate entity working. 
For water heater entity, it looks like your device does not have tank, but flow-through without temp sensor, so could be difficult to get working. Also it does not have "Powerful" mode, which could cause additional errors if not disabled in code.

Hints for changing code for climate entity (so files in /config/custom_components/daikin_residential_brp069a62 folder):

In const.py: lines 57-59, replace with
```
ATTR_HVAC_MODE_COOL = "heatingDay"
ATTR_HVAC_MODE_HEAT = "heatingDay"
ATTR_HVAC_MODE_AUTO = "heatingNight"
```

In climate.py: line 127, replace:
`return self._device.leavingWater_temperature`
with:
`return self._device.inside_temperature`

In daikin_base.py: line 268, replace:
`return await self.setValue(ATTR_TARGET_TEMPERATURE, int(value))`
with:
`return await self.setValue(ATTR_TARGET_TEMPERATURE, float(value))`

In device.py line 218, replace
`+ str(type(descr["value"]))`
with
`+ str(type(descr["stepValue"]))`

For water heater you may try:
In water_heater.py: line 118, replace:
`return self._device.dhw_temperature`
with:
`return self._device.dhw_target_temperature`

Let me know how it goes.

**Comment by mihsu81** [comment]
Thanks a lot @BigFoot2020. It worked fine.
Now I'll have to find a way to match the Day/Night schedule of my specific setup, remove the cooling part and adjust the water heater.

**Comment by mihsu81** [comment]
Hi @BigFoot2020,

tadasdanielius was able to implement support for this gas boiler in his "Daikin Altherma" integration (which I think you're using as well). https://github.com/tadasdanielius/daikin_altherma/issues/31
For the sake of availability, would you be willing/available to implement his changes in your integration?
Thanks in advance.

**Comment by BigFoot2020** [comment]
I would be willing to implement this, but I simply lack the knowledge needed to do that. My current opinion is that with current architecture it is not possible to properly support different setups. That probably was the main reason why I had to create this repository, as it was too difficult to add support for my device to original repository.

As I see there is 2 options:
1. Create a fork (or new repository as I did) for your setup and implement needed changes there. I'm willing to help as much as I can.
2. Rebuild from scratch so that new implementation would support different devices (theoretically any device that is supported Daikin ONECTA app). Unfortunately this would be way too difficult for me, so unless you know a developer would could help it's not going to happen.

**Comment by BigFoot2020** [comment]
In case interested [Daikin Residential for Altherma](https://github.com/speleolontra/daikin_residential_altherma/) now supports BRP069A62. You may want try if it also works for your system.

**Comment by jwillemsen** [comment]
It looks there is a custom schedule in the json provided, that seems to change the available operation modes. At the moment you want HA to control your alterma don't use a schedule at the daikin side, let HA control your altherma completely.

**Comment by mihsu81** [comment]
It looks like with https://github.com/speleolontra/daikin_residential_altherma/ the gas boiler is not detected at all.
There aren't any warnings or errors in System/Logs.

**Comment by jwillemsen** [comment]
Can you try https://github.com/jwillemsen/daikin_residential_altherma/tree/jwi-energyconsumption, it looks your device has NDJ as model, the data looks similar. Please enable debug logging of the integration, see the readme for how to do that.

**Comment by mihsu81** [comment]
It's still not detected. 
[config_entry-daikin_residential_altherma-3b2087cef25bfec6fe832a003d21a4e2.json.txt](https://github.com/BigFoot2020/daikin_residential_brp069a62/files/11060153/config_entry-daikin_residential_altherma-3b2087cef25bfec6fe832a003d21a4e2.json.txt)

**Comment by jwillemsen** [comment]
Please enable debug logging, see https://github.com/speleolontra/daikin_residential_altherma#setting-the-log-level, restart HA and attach your HA log

**Comment by mihsu81** [comment]
Here it is. 🤞
[config_entry-daikin_residential_altherma-3b2087cef25bfec6fe832a003d21a4e2.json.txt](https://github.com/BigFoot2020/daikin_residential_brp069a62/files/11060315/config_entry-daikin_residential_altherma-3b2087cef25bfec6fe832a003d21a4e2.json.txt)

**Comment by jwillemsen** [comment]
That is the json file, I need the debug log, you can get it from settings/system/logs/download full log

**Comment by mihsu81** [comment]
Whoops. 😁
[home-assistant_2023-03-24T09-16-42.450Z.log](https://github.com/BigFoot2020/daikin_residential_brp069a62/files/11060341/home-assistant_2023-03-24T09-16-42.450Z.log)

**Comment by jwillemsen** [comment]
Did you checkout my test branch, you log says

```
2023-03-24 11:05:49.819 INFO (MainThread) [custom_components.daikin_residential_altherma.daikin_api] Found device 'NDJ' with gateway model 'DRGATEWAYAA'
2023-03-24 11:05:49.819 INFO (MainThread) [custom_components.daikin_residential_altherma.daikin_api] Device 'NDJ' with gateway model 'DRGATEWAYAA' is filtered out because it is not an Altherma model
```

But I changed the error message to contain `out because it is not a supported model`

**Comment by BigFoot2020** [comment]
2 integrations (BRP... and Althrema) would be trying to add same device with same name, this may cause issues (confirmed this on my test HA). 
Would it be possible for you to set up separate test HA with only daikin_residential_altherma added?
If not, then you may want to remove daikin_residential_brp069a62 first.

**Comment by mihsu81** [comment]
Hi @jwillemsen,

I completely uninstalled the integration, rebooted HA and added it again. I've also removed @BigFoot2020's integration.
I've also installed it on another HA instance on another device.
In both cases the device is not added.
[config_entry-daikin_residential_altherma-c7d15f04b22b860e46d607d5d8169eb0.json.txt](https://github.com/BigFoot2020/daikin_residential_brp069a62/files/11062116/config_entry-daikin_residential_altherma-c7d15f04b22b860e46d607d5d8169eb0.json.txt)
[config_entry-daikin_residential_altherma-1c9e024d0b9b240251997e2481ee6aca.json.txt](https://github.com/BigFoot2020/daikin_residential_brp069a62/files/11062118/config_entry-daikin_residential_altherma-1c9e024d0b9b240251997e2481ee6aca.json.txt)

**Comment by jwillemsen** [comment]
Please attach the log, that should give me some more ideas

**Comment by mihsu81** [comment]
Sorry, I thought I did.
[home-assistant_2023-03-24T14-18-16.197Z.log](https://github.com/BigFoot2020/daikin_residential_brp069a62/files/11063128/home-assistant_2023-03-24T14-18-16.197Z.log)
[home-assistant_2023-03-24T14-21-24.882Z.log.txt](https://github.com/BigFoot2020/daikin_residential_brp069a62/files/11063135/home-assistant_2023-03-24T14-21-24.882Z.log.txt)

**Comment by jwillemsen** [comment]
Both logs don't have "it is not a supported model", but the old message "because it is not an Altherma model", are you sure you checked out my branch on your system?

**Comment by mihsu81** [comment]
In HACS appears your fork, but when i check it in Devices & Services after adding it, I see the main integration from speleolontra.
Do I have to do anything else except adding https://github.com/jwillemsen/daikin_residential_altherma/tree/jwi-energyconsumption as a custom repo in HACS and downloading it?
![image](https://user-images.githubusercontent.com/40715497/227554310-fd838836-0173-46b3-9bf2-ca95b5333e58.png)

**Comment by jwillemsen** [comment]
I don't use HACS regulary, I use git directly, you can use ` git clone --branch jwi-energyconsumption https://github.com/jwillemsen/daikin_residential_altherma` to clone the source code, take the files you get in the new `daikin_residential_altherma` directory and replace the files that HACS has put on disc, and restart HA

**Comment by BigFoot2020** [comment]
I have "Samba share" add-on enabled in HA. So I download repo as zip, extract and copy needed file to share, then restart HA.

**Comment by jwillemsen** [comment]
Ok, on https://github.com/jwillemsen/daikin_residential_altherma/tree/jwi-energyconsumption you can download the zip, attach the logs here again, let us see what happens when we relax the check for the model

**Comment by mihsu81** [comment]
The device gets created after replacing the files, but it's missing the controls because of climate restrictions.

```
Log Details (ERROR)
Logger: homeassistant.components.climate
Source: custom_components/daikin_residential_altherma/daikin_base.py:157
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 16:20:24 (4 occurrences)
Last logged: 16:21:36

Error adding entities for domain climate with platform daikin_residential_altherma
Error while setting up daikin_residential_altherma platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 629, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 262, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/daikin_residential_altherma/climate.py", line 307, in hvac_modes
    return self._device.hvac_modes
  File "/config/custom_components/daikin_residential_altherma/daikin_base.py", line 157, in hvac_modes
    modes.append(DAIKIN_HVAC_TO_HA[mode])
KeyError: 'heatingDay'
```

![image](https://user-images.githubusercontent.com/40715497/227568765-0e2f4f7b-e182-4944-a162-4c6cf2d3864c.png)

**Comment by jwillemsen** [comment]
Can you pull my branch and try again, made a small addition for the special operation modes, see https://github.com/speleolontra/daikin_residential_altherma/pull/139/commits/5ab50b541d439aeb5381c78c010ac1dbaf37b61a

**Comment by jwillemsen** [comment]
One question, is heatingDay/heatingNight a custom schedule you have or is that something standard for this device? If this is your custom schedule, can you try to remove it so that you just heave `heating` as operation mode

**Comment by mihsu81** [comment]
The climate entity gets created now but both actions are Heat.

heatingDay and heatingNight are the 2 working modes of the device.

There are also 2 possible schedules which can be enabled on the boiler. 

![image](https://user-images.githubusercontent.com/40715497/227574808-8f64bec7-e684-4671-8dd5-af65e16a344b.png)

**Comment by jwillemsen** [comment]
Ok, made another change to just have one heat. Day/night is something that very likely something that should be a preset_mode, but that is too much work at this moment, need to think about how to add that in a clean way. Shall I merge the changes I have now, that at least gives you some support?

**Comment by mihsu81** [comment]
Thanks a lot guys for all the work you put into this.

I only get Heat and Off now and I can adjust the temperature.

![image](https://user-images.githubusercontent.com/40715497/227588223-7b7df10f-a9d8-46d2-a3bd-5884387898ca.png)

 The water_heater device is not added by the integration.

![image](https://user-images.githubusercontent.com/40715497/227588770-b1590b62-5d5b-4151-9600-19603bdff751.png)


This is another approach to control the gas boiler from the local integration. https://github.com/tadasdanielius/daikin_altherma

![image](https://user-images.githubusercontent.com/40715497/227586482-13de9421-a03b-46d6-ac77-a87871458bc8.png)

**Comment by jwillemsen** [comment]
Please attach a new log, maybe the watertank is just a small issue

**Comment by mihsu81** [comment]
Here it is.
[home-assistant_2023-03-24T17-14-21.248Z.log](https://github.com/BigFoot2020/daikin_residential_brp069a62/files/11064804/home-assistant_2023-03-24T17-14-21.248Z.log)

**Comment by jwillemsen** [comment]
@mihsu81 Ok, there are two issues for the water tank, one is easy, there is no separate tankTemperature sensor, so I can check the availability of the management point. But, the management point for your device is called `domesticHotWaterFlowThrough` and with the altherma3 it is `domesticHotWaterTank`. The way the code is currently structured this is not a simple change, it requires https://github.com/speleolontra/daikin_residential_altherma/issues/86 to be implemented which is a large structural change, not sure when I get enough spare time to try that.

**Comment by mihsu81** [comment]
Ok, then I guess we can go ahead with support in the current state and will add more as you have time.

**Comment by jwillemsen** [comment]
Yes, maybe some time next week to try the new approach for just the water tank
