### ISSUE TITLE
BRP069A78

### ISSUE THREAD

**Issue by EvertJob** [BigFoot2020/daikin_residential_brp069a62#5]
Hi,

Is there any one who got the BRP069A78 working on this plugin?

I've installed it and configured it in HA where I got a successfully login but no devices/entities are showing.

In my logs I'm seeing this line where the `Device ID` is matching with the Device ID I'm seeing in the Daiking app.

```2022-03-22 10:58:13 WARNING (MainThread) [custom_components.daikin_residential_brp069a62.daikin_api] Device with ID '8066d70a-84fa-40d4-803f-247562b67c21' is filtered out```

**Comment by BigFoot2020** [comment]
This integration is specifically for BRP069A61/2. It will not work for A78 as data structure in Daikin cloud is too different.
You should look at integration from Speleolontra "daikin_residential_altherma" (https://github.com/speleolontra/daikin_residential_altherma), that should be for your device.
